"""Added address model

Revision ID: 0c0faf0b6ee4
Revises: 
Create Date: 2024-09-24 14:49:13.414144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0faf0b6ee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=200), nullable=False),
    sa.Column('postalCode', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('neighbourhood', sa.String(length=1000), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('houseNumber', sa.String(length=200), nullable=True),
    sa.Column('apartmentNumber', sa.String(length=200), nullable=True),
    sa.Column('contactPhone', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
