"""Changed exampleVar to example_var in address model

Revision ID: 31f4e0254c08
Revises: 0c0faf0b6ee4
Create Date: 2024-09-24 19:24:50.702851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f4e0254c08'
down_revision = '0c0faf0b6ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('house_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('apartment_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=200), nullable=False))
        batch_op.drop_column('apartmentNumber')
        batch_op.drop_column('houseNumber')
        batch_op.drop_column('contactPhone')
        batch_op.drop_column('fullName')
        batch_op.drop_column('postalCode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postalCode', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fullName', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('contactPhone', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('houseNumber', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('apartmentNumber', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('apartment_number')
        batch_op.drop_column('house_number')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
